### ISSUE TITLE
Plugin was not found in any of the following sources

### ISSUE THREAD

**Issue by ipgaero** [openjfx/openjfx-docs#102]
Hi I`m trying to run HelloFx project. I tried to create it manually or ran github project but get the same error. Could you help me ?

Error: **Plugin [id: 'org.openjfx.javafxplugin', version: '0.0.7'] was not found in any of the following sources:**

github project was from: https://github.com/openjfx/samples/tree/master/HelloFX/Gradle
details on screeshort: https://yadi.sk/i/FAOsg6xESOqcmA

**Comment by jperedadnr** [comment]
What happens if you try from a terminal? On the root of the project run:
`gradlew clean build run`

If that works, the problem could be related to IntelliJ.

Else, check your internet settings (firewall, proxy, ...).

You could try also this instead:

```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'org.openjfx:javafx-plugin:0.0.7'
    }
}
apply plugin: 'org.openjfx.javafxplugin'
```

**Comment by ipgaero** [comment]
The both ways did not help much, you may look at results on the screens folowing by the links. I`ll try google may be found something

https://yadi.sk/i/oCHLSz-L4f5lLQ
https://yadi.sk/i/fg7ai8vlkcR_xQ

**Comment by jperedadnr** [comment]
Gradle plugin is published here: https://plugins.gradle.org/m2/, can you access that link from a regular browser?

Can you try any other gradle plugin?

(Maven plugin goes to Maven Central)

**Comment by ipgaero** [comment]
Yes, I have accsess that link from a regular browser
I tried different plugin It didn`t work out either
I guess it`s some network issue

**Comment by ipgaero** [comment]
eventually I managed to run projects, the issue was antivirus settings for network
