### ISSUE TITLE
Is there any way to get JavaFX to run on an old version of Linux?

### ISSUE THREAD

**Issue by gforman44** [openjfx/openjfx-docs#104]
**Is there any way to get JavaFX to run on an old version of Linux?**   Java Swing runs fine, but JavaFX fails.  Details follow:

When I follow the Linux instructions here[1], I get the same errors as Michael did in issue #69 here[2]:
>     JavaFX 11.0.2: QuantumRenderer: no suitable pipeline found 
but he was on Mac and had downloaded the wrong libraries.  I'm on Linux and have downloaded the right v11 libraries[3].  

The problem is that I'm on an OLD version of Linux[4] (which I can't upgrade for various reasons).  Is there any way to get JavaFX to run on an old version of Linux?

Finally, when I follow the instructions here 
https://github.com/openjfx/samples/blob/master/CommandLine/Modular/CLI/README.md
I get this error:
libGL error:  unable to load driver: swrast_dri.so
libGL error:  failed to load driver swrast
Prism-ES2 Error : GL_VERSION (major.minor) = 1.4
Graphics Device initialization failed for :  es2, sw
Error intializing QuantumRenderer: no suitable pipline found
java.lang.RuntimeException:  java.lang.RuntimeException:  Error initializing QuantumRenderer: no suitable pipeline found

Thanks,
George

[1] https://openjfx.io/openjfx-docs/#install-javafx   using the LINUX instructions
[2] https://github.com/openjfx/openjfx-docs/issues/69
[3] java --version
openjdk 11.0.3 2019-04-16 LTS
....
export PATH_TO_FX=$HOME/javafx-sdk-11.0.2/lib
javac --module-path $PATH_TO_FX  --add-modules javafx.controls   HelloFX.java
(worked fine)
java --module-path $PATH_TO_FX  --add-modules javafx.controls   HelloFX
Graphics Device initialization failed for :  es2, sw

[4] % cat /etc/*release
Red Hat Enterprise Linux Server release 5.3 (Tikanga)
Amazon Linux Bare Metal release 2012.03
% uname -a
Linux kernel 4.9.152-0.1.ac.221.y79.329.metal1.x86_64 GNU/Linux

I'm running Xvnc.  Java Swing runs fine.

**Comment by abhinayagarwal** [comment]
This repository handles only documentation for openjfx.io :)

Please report this issue on OpenJFX Github mirror repository: https://github.com/javafxports/openjdk-jfx/
