### ISSUE TITLE
Criteria for listing a project under Community

### ISSUE THREAD

**Issue by aalmiray** [openjfx/openjfx-docs#11]
What's the criteria for listing a project under the "Community" space?
Is there a limit?

**Comment by eugener** [comment]
No limits. But has to work with JavaFX 11

**Comment by aalmiray** [comment]
Well in that case there are 5 projects listed at http://andresalmiray.com/more-javafx-related-announcements/ that have been tested with JavaFX 11. HarmonicFX is listed as pending because 2 widgets still rely on JavaFX 8 API, the rest of the library is OK.

Currently I see the site listing projects using:
 - a screenshot
 - project label
 - short description

Should I send separate PRs for each project then?

**Comment by eugener** [comment]
Each project element is also a link to the related site or repository. The PR would be best. You don't have to do multiple PRs - one with all the projects should be enough, just make sure all of them run under JavaFX 11
