### ISSUE TITLE
"Run HelloWorld via Gradle" section is missing module.

### ISSUE THREAD

**Issue by SamuelPommer** [openjfx/openjfx-docs#110]
`javafx {
    version = "12.0.2"
    modules = [ 'javafx.controls' ]
}`
Is what the "Run HelloWorld via Gradle" section of "Getting Started with JavaFX 12" says. [This](https://openjfx.io/openjfx-docs/#gradle).
After trying to get it to run, FXML annotations couldn't be resolved.
I then compared the Gradle and commandline setup and saw that 'javafx.fxml' was not imported.
What the tutorial should say is:
`javafx {
    version = "12.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}`
So that fxml is also imported, without which the controller won't work.

**Comment by jperedadnr** [comment]
The referred sample is https://github.com/openjfx/samples/tree/master/HelloFX/Gradle, and it only requires `javafx.controls`. 

If you run other samples, some of then have FXML, and therefore they include `javafx.fxml`, like this one: https://github.com/openjfx/samples/tree/master/IDE/IntelliJ/Non-Modular/Gradle/hellofx
