### ISSUE TITLE
runtime error - run HelloWorld

### ISSUE THREAD

**Issue by physcrowley** [openjfx/openjfx-docs#112]
I've been following the instructions and have been able to compile the .java file, but cannot run it.

Here is the error I receive from the command line:
````
C:\Users\crowlda>javac --module-path %PATH_TO_FX% --add-modules javafx.controls,javafx.fxml C:\users\crowlda\Documents\workspace\HelloFX\src\HelloFX.java

C:\Users\crowlda>java --module-path %PATH_TO_FX% --add-modules javafx.controls C:\users\crowlda\Documents\workspace\HelloFX\src\HelloFX
Error: Could not find or load main class C:\users\crowlda\Documents\workspace\HelloFX\src\HelloFX
Caused by: java.lang.ClassNotFoundException: C:\users\crowlda\Documents\workspace\HelloFX\src\HelloFX
````

Any ideas why this is happening? I am very new to this, so I don't have much experience or knowledge for troubleshooting these types of problems.

**Comment by jperedadnr** [comment]
Make sure you have created (or [downloaded](https://github.com/openjfx/samples/blob/master/HelloFX/CLI/hellofx/HelloFX.java)) the HelloFX.java file into that folder `C:\users\crowlda\Documents\workspace\HelloFX\src`.

**Comment by physcrowley** [comment]
The HelloFX.java file wasn't in the folder! I thought that it must have been because the compiler just executed on that file path without throwing an error.
