### ISSUE TITLE
--add-modules parameter in NetBeans Ant VM options does not recognise javafx modules

### ISSUE THREAD

**Issue by zaeima** [openjfx/openjfx-docs#115]
Hello, I'm trying to run this [JavaFX application](https://github.com/openjfx/openjfx-docs/files/3631167/Calculator.java.txt) using JDK 11 and OpenJFX 11.0.2 in NetBeans on linux.

I followed the instructions for running a [non-modular project from IDE](https://openjfx.io/openjfx-docs/#IDE-NetBeans), and I was able to successfully compile the program without any errors.

However, when I tried to modify the runtime VM options in the project properties to include the modules javafx.controls and javafx.fxml and ran the project, I got the error:
`Error occurred during initialization of boot layer`
`java.lang.module.FindException: Module javafx.controls not found`

I tried to change the syntax of the add modules statement, added and removed equal signs, removed spaces, however the VM was still unable to recognise the imported modules. I even tried changing the modules that I imported, however each time it was unable to find the module that I specified. I am certain that the javafx module jar files are inside the --module-path that I specified, within the lib folder.

This is the details that show up when I click the "Re-run with Different Parameters" button on the run window:
![RerunWithDifferentParameters](https://user-images.githubusercontent.com/53345576/65245518-4eba4000-dadc-11e9-85cc-16f39d1ab933.png)

**Comment by profjpbaugh** [comment]
I am having the exact same issue.  I have followed the instructions to the 'T' and I get the error as indicated above:
```
run:
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found
C:\Users\jpbau\AppData\Local\NetBeans\Cache\11.1\executor-snippets\run.xml:111: The following error occurred while executing this line:
C:\Users\jpbau\AppData\Local\NetBeans\Cache\11.1\executor-snippets\run.xml:68: Java returned: 1
BUILD FAILED (total time: 0 seconds)
```

This is quite frustrating, to say the least.  I've made all sorts of modifications trying to get this to work and to no avail.  It's upsetting moving from NetBeans 8.2 where you could just say, "Make a JavaFX application", and "boom!", you had one.  Although the installer for Apache NetBeans has made the general Java setup easier, JavaFX remains an enigma and I have yet to be able to get it to run properly.

**Comment by jperedadnr** [comment]
Have you tried the related [HelloFX sample](https://github.com/openjfx/samples/tree/master/IDE/NetBeans/Non-Modular/Java/hellofx)?

This should work for you (Java 11+, JavaFX 11+, Apache NetBeans 11.1).

One of the possible fixes for the mentioned issues is to add the JavaFX11+ library to the Library options: `Properties -> Libraries -> Run -> Modulepath`. 

With this option, you can skip the VM option `--module-path` (as the above will take precedence).

This is possibly the reason for the issues: NetBeans adds a second `--module-path` that overrides the one from VM options.

**Comment by zaeima** [comment]
> One of the possible fixes for the mentioned issues is to add the JavaFX11+ library to the Library options: `Properties -> Libraries -> Run -> Modulepath`.
> 
> With this option, you can skip the VM option `--module-path` (as the above will take precedence).

I added the JavaFX11 Library under the Modulepath section in the `Properties -> Libraries -> Run` menu, and then removed the --module-path parameter in the VM options, and I was able to run my application. Thanks for the help!

**Comment by nvaranki** [comment]
I confirm it works on NetBeans 12.0, Gluon JavaFX 15 and Open Java SDK 15. Kind thanks!
![NetBeans-1S](https://user-images.githubusercontent.com/23263557/101775642-d4227980-3b00-11eb-8fd5-92477850754d.png)
![NetBeans-2S](https://user-images.githubusercontent.com/23263557/101775947-47c48680-3b01-11eb-9b0d-fab5080bee8d.PNG)

**Comment by jcvasquez07** [comment]
I had the same issue and solved it by unchecking the 'compile on save' option (Project properties - Compiling). Apparently the nb-javac plugin is the one causing this error

**Comment by simple-carllos** [comment]
To resolve this issue, in the Project properties, click on Libraries. Select the Run tab and make your Modulepath the same as you did for the Class path in the Compile tab.

**Comment by ArisnordEvenson** [comment]
--add-modules javafx.controls,javafx.fxml,javafx.media

this is the way i was trying to configure it.

**Comment by ArisnordEvenson** [comment]
--add-modules javafx.controls,javafx.fxml,javafx.media
this the way i was trying to configure it.
