### ISSUE TITLE
Getting Started Guide for JavaFX 13 Confusing

### ISSUE THREAD

**Issue by mvfranz** [openjfx/openjfx-docs#119]
The getting started guide (https://openjfx.io/openjfx-docs/#install-java) for JavaFX 13 is confusing by talking about Java 13 but showing screenshots for Java 12.  Is Java 12 or Java 13 required to install JavaFX 13?

**Comment by profjpbaugh** [comment]
I spent several hours creating a corrected and more thorough guide for Windows installation of OpenJDK 13, NetBeans 11.1, OpenJFX (JavaFX), and Scene Builder.  I hope you (and others) find this useful:

https://github.com/profjpbaugh/apache-netbeans-openjdk-openjfx

If you already have NetBeans installed or another IDE, hopefully this will help out a bit.

**Comment by Mason-Chou** [comment]
To be safe, it should be Java 13. You should try to match your version of JavaFX to your Java version (JavaFX 11 to Java 11, JavaFX 13 to Java 13, etc...). 

This [PR](#116 ) addresses this issue.

**Comment by abhinayagarwal** [comment]
Fixed by PR #141
