### ISSUE TITLE
Run HelloWorld using Gradle document is confusing.

### ISSUE THREAD

**Issue by vegaonline** [openjfx/openjfx-docs#121]
Hello!
I was following the javafx documentation. I see description on build.gradle. However, it is not clear how gradle/wrapper files (like jar file) could be obtained. Also `"./gradlew run"` shows 
`"Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain"`.

I have 
`$ java -version
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)`

and

`$ gradle -v`

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/share/java/groovy-all.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

`Gradle 4.4.1`

`Build time:   2012-12-21 00:00:00 UTC
Revision:     none`

`Groovy:       2.4.16
Ant:          Apache Ant(TM) version 1.10.5 compiled on March 28 2019
JVM:          13.0.1 (Oracle Corporation 13.0.1+9)
OS:           Linux 4.15.0-65-generic amd64`

The ERROR showing illegal reflective access does not appear if I use jre 1.8.0.

Please suggest how may I run? 
Thanks

**Comment by Mason-Chou** [comment]
The doc says to use gradle version 4.10+. Try updating your gradle version and it should work out.

**Comment by abhinayagarwal** [comment]
Java 13 is only supported with Gradle 6.0+
