### ISSUE TITLE
Error: Could not find or load main class HelloFX

### ISSUE THREAD

**Issue by arbeDE** [openjfx/openjfx-docs#123]
D:\Clone\Test88\Test88\src\test88>java --module-path %PATH_TO_FX% --add-modules
javafx.controls HelloFX
Error: Could not find or load main class HelloFX
Caused by: java.lang.NoClassDefFoundError: test88/HelloFX (wrong name: HelloFX)

D:\Clone\Test88\Test88\src\test88>echo %PATH_TO_FX%
D:\Clone\javafx-sdk-13.0.1\lib

D:\Clone\Test88\Test88\src\test88>echo %JAVA_HOME%
C:\Program Files\Java\jdk-13.0.1

D:\Clone\Test88\Test88\src\test88>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Wind
owsPowerShell\v1.0\;D:\Clone\javafx-sdk-13.0.1\bin;C:\Program Files\Java\jdk-13.0.1\bin

 Directory of D:\Clone\Test88\Test88\src\test88

11/03/2019  06:09 AM    <DIR>          .
11/03/2019  06:09 AM    <DIR>          ..
11/03/2019  06:09 AM             1,451 HelloFX.class
11/03/2019  06:08 AM             1,068 HelloFX.java
               2 File(s)          2,519 bytes
               2 Dir(s)  53,572,710,400 bytes free

D:\Clone\Test88\Test88\src\test88>java --module-path %PATH_TO_FX% --add-modules
javafx.controls HelloFX
Error: Could not find or load main class HelloFX
Caused by: java.lang.NoClassDefFoundError: test88/HelloFX (wrong name: HelloFX)

**Comment by GeoffroyFunck** [comment]
I had the same problem and find this solution: 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Add  "**--class-path .**" to the java command line i.e. :

`> java `**`--class-path .`**` --module-path "%PATH_TO_FX%" --add-modules javafx.controls HelloFX`
I expect this helps

**Comment by abhinayagarwal** [comment]
Your class file has a package declaration with `package test88;` ?

Your `java` command needs to be fired from the `src` directory and needs to be updated to:

```
D:\Clone\Test88\Test88\src> java --module-path %PATH_TO_FX% --add-modules javafx.controls test88.HelloFX
```

**Comment by NathanPaceydev** [comment]
** If you are having this error on Eclipse**
"Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found"

Remove the JavaFX SDK library from the build path of the project!!

**Comment by pranshu7800** [comment]
> ** If you are having this error on Eclipse**
> "Error occurred during initialization of boot layer
> java.lang.module.FindException: Module javafx.controls not found"
> 
> Remove the JavaFX SDK library from the build path of the project!!

will it create any problem to my javafx program?
