### ISSUE TITLE
Regression bug in javafx.media

### ISSUE THREAD

**Issue by JoHaHu** [openjfx/openjfx-docs#126]
Hello,

I've created a sample  [project](https://github.com/JoHaHu/javafx-regression-bug)  to show the issue.

I'm using java 13 (tried adoptjdk and openjdk in version 12 and 13) on archlinux. When i change the javafx version from 12 to 13 or above, the mediaplayer doesn't get created and throws an MediaExcpetion.
Javafx 12 works. I assume i have all necessary codecs (ffmpeg 54-64) installed.

**Comment by abhinayagarwal** [comment]
This is not related to the documentation. Please post this in the openjfx-dev mailing list to discuss further.
