### ISSUE TITLE
Mistake on the tutorial description "JavaFX and IntelliJ"

### ISSUE THREAD

**Issue by vl0ft** [openjfx/openjfx-docs#127]
On tutorial page "JavaFX and IntelliJ"->"Non-modular with Maven" and "JavaFX and IntelliJ"->"Modular with Maven" in chapter **3. Run the project**:
step `HelloFX -> Plugins -> compiler -> compiler:compile` isn't work. 
I suppose there is should be `HelloFX -> Plugins -> compiler -> javafx:compile`.

![image](https://user-images.githubusercontent.com/16957102/69485038-8088b380-0e4b-11ea-99db-fe66ea0e81ca.png)

**Comment by myucesan** [comment]
This issue has still not been resolved.

**Comment by abhinayagarwal** [comment]
Can someone create a PR?

**Comment by myucesan** [comment]
> 
> 
> Can someone create a PR?

I just created a pull request for the documentation.

**Comment by abhinayagarwal** [comment]
Hi @myucesan,

`javafx:compile` goal has been removed in recent version of javafx-maven-plugin` deprecating this issue.
