### ISSUE TITLE
had to make changes to get example to work

### ISSUE THREAD

**Issue by Joe-Schmo** [openjfx/openjfx-docs#128]
In the example  samples-master.zip\samples-master\IDE\NetBeans\Modular\Maven\hellofx, I had to make 2 changes to make it run.

First in App.java I had to change
FXMLLoader fxmlLoader = new FXMLLoader(App.class.getResource(fxml + ".fxml"));
to
 FXMLLoader fxmlLoader = new FXMLLoader(App.class.getResource("/org/openjfx/"+fxml+".fxml"));

Also I had to change to 2 controller methods from private to public.

Should I have had to do this?

**Comment by myucesan** [comment]
Follow this [guide](https://openjfx.io/openjfx-docs/#install-javafx) instead of directly trying to run an example so you can be sure you have everything set up correctly.

**Comment by abhinayagarwal** [comment]
@Joe-Schmo Can you mention the name of the methods?

**Comment by abhinayagarwal** [comment]
No updates from the reporter.
