### ISSUE TITLE
No main manifest

### ISSUE THREAD

**Issue by sLasHee** [openjfx/openjfx-docs#130]
I use plugin: <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.3</version>
and have jar-file with mistake: no main manifest

**Comment by abhinayagarwal** [comment]
Hi,

Thank you for opening the issue. If you think javafx-maven-plugin has an bug or you want a feature, please report in this repository: https://github.com/openjfx/javafx-maven-plugin
