### ISSUE TITLE
I get garbage in HelloFX (Mac OSX Catalina)

### ISSUE THREAD

**Issue by DavidBarts** [openjfx/openjfx-docs#131]
Just built HelloFX per the instructions and I get line of unreadable garbage instead of the expected messages. Screen shot here:
http://blackcap.name/blog/new/wp-content/uploads/2020/01/Screen-Shot-2020-01-04-at-17.34.11.png

This is with javafx-sdk-13.0.1.

java -fullversion says:
openjdk full version "13.0.1+9"

**Comment by abhinayagarwal** [comment]
Please file this bug in JBS or write to openjfx-dev mailing list with a reproducible example.

**Comment by DavidBarts** [comment]
1. What is this "JBS"?
2. Why even have this issues page here on Github if all that filing an issue here gets one is a curt and cryptic comment to use "JBS"?
3. The "test case," as mentioned already is the HelloFX program given in this very github repository: https://github.com/openjfx/samples/blob/master/HelloFX/CLI/hellofx/HelloFX.java
4. Let me just add that a software package that cannot even properly run the "hello, word" script listed on its very own web site does not exactly inspire confidence as to its quality or usability.

**Comment by abhinayagarwal** [comment]
1. JBS is [JDK Bug System](https://bugs.openjdk.java.net/secure/Dashboard.jspa)
2. The OpenJFX-docs issue page is to deal with an issue with the sample/documentation itself, and not with an issue in JavaFX
3. You have a reproducible example. Shoot a mail to [OpenJFX-dev mailing list](https://mail.openjdk.java.net/mailman/listinfo/openjfx-dev). The list has most JavaFX platform developers who can help you with any issue with the platform
4. All platforms can have issues. A quick Google search landed me to this issue [JDK-8234916](https://bugs.openjdk.java.net/browse/JDK-8234916), which shows that this issue with JavaFX 13 has been fixed
