### ISSUE TITLE
Error: Could not find or load main class Files/Java/openjfx-13.0.2_windows-x64_bin-sdk\javafx-sdk-13.02\lib 

### ISSUE THREAD

**Issue by rh0155689** [openjfx/openjfx-docs#137]
Error: Could not find or load main class Files\Java\openjfx-13.0.2_windows-x64_bin-sdk\javafx-sdk-13.0.2\lib
Caused by: java.lang.ClassNotFoundException: Files\Java\openjfx-13.0.2_windows-x64_bin-sdk\javafx-sdk-13.0.2\lib

Hi. See above for the error that I get when I try to run the program from the tutorial. I am having the same issue whether I use the community or the ultimate version of Intellij IDEA. I have followed the tutorial to a T as well as followed along with a YouTube video by Kody Simpson that basically followed the tutorial as well. Everything for me goes exactly as the video until I get to the part where I select: 

 Run - Edit Configuration - Copy/Paste  --module-path "\path\to\javafx-sdk-13\lib" --add-modules javafx.controls,javafx.fxml 

.... but with the path to my JavaFX library between the double quotes. When I try to run the program after the above step is when I get the error.

**Comment by abhinayagarwal** [comment]
Your issue is with the "path" of the JavaFX SDK. Instead of `C:\Program Files\Java...`, the IDE is reading `Files\Java\...`.
