### ISSUE TITLE
Error: JavaFX runtime components are missing, and are required to run this application

### ISSUE THREAD

**Issue by SergeyKotlyar** [openjfx/openjfx-docs#147]
Hello, and sorry for the bad English.
I have Windows 10 64bit, NetBeans 11.3, JavaFX 14 SDK.
I wrote an application in JavaFX, but I can’t use Java 14 SDK with JavaFX 14.
I tried all your examples from https://openjfx.io/openjfx-docs/
Unfortunately, nothing works. Error occurs: JavaFX runtime components are missing, and are required to run this application
I followed all your recommendations in the code examples, but this error still appears.
Please, help. I probably missed something and am not doing it or doing something wrong. Because of this error, I can only run in Java version 8.251 and not higher.
Thanks in advance.

**Comment by patoessy** [comment]
Are you using gradle or maven. And if so just post your pom.xml or
build.gradle

**Comment by SergeyKotlyar** [comment]
These are the messages when starting the Maven project.

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default-cli) on project MavenFX: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default-cli) on project MavenFX: Command execution failed.

and pom.xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>MavenFX</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>14</maven.compiler.source>
        <maven.compiler.target>14</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>13</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>13</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.3</version>
                <configuration>
                    <mainClass>com.mycompany.mavenfx.App</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by jamesz-hub** [comment]
Was this issue fixed?
