### ISSUE TITLE
Does OpenJFX supports OpenJDK 1.8?

### ISSUE THREAD

**Issue by vigneshrcsengg** [openjfx/openjfx-docs#152]
Unable to compile my existing project with same OpenJDK 1.8 with OpenJFX11. 
I have gone through the OpenJFX installation guide [Install OpenJFX](https://openjfx.io/openjfx-docs/#install-javafx) with an example project. 
But still unable to make it with JDK1.8. As per client dependencies, the JDK version should be 1.8

It triggers error as below while building the project in Netbeans

`C:\Users\vignesh.rajendran\Documents\NetBeansProjects\HelloFX\src\hellofx\Controller.java:8: error: cannot access FXML
import javafx.fxml.FXML;
  bad class file: C:\Users\vignesh.rajendran\Documents\NetBeansProjects\HelloFX\lib\JavaFX11\javafx.fxml.jar(javafx/fxml/FXML.class)
    class file has wrong version 54.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
BUILD FAILED (total time: 1 second)`

**Comment by eugener** [comment]
OpenJDK 1.8 includes JavaFX - no special setup needed.
Starting with OpenJDK11, JavaFX is distributed separately as OpenJFX. The libraries are compiled for Java 11 and cannot be used with Java 8, that is why you see "wrong class file version" error.

**Comment by vigneshrcsengg** [comment]
Thanks for the clarification, I will use Open JDK 11 and Open JFX 11.
