### ISSUE TITLE
openjfx.io site: wrong link to reference documentation on "Getting Started" page

### ISSUE THREAD

**Issue by badscrew** [openjfx/openjfx-docs#174]
Hello,
The link titled "detailed reference documentation for JavaFX" on the page [https://openjfx.io/openjfx-docs/](https://openjfx.io/openjfx-docs/) points to [https://docs.oracle.com/javase/8/javase-clienttechnologies.htm](https://docs.oracle.com/javase/8/javase-clienttechnologies.htm) instead of wherever it should be pointing to.

**Comment by johanvos** [comment]
Thanks for reporting.
I discussed this with a number of people, and the main issue is that the "wherever it should be pointing to" doesn't exist. The old overview (JavaFX 8 based) on the Oracle site is still, from a conceptual point, a good overview. 
However, many internal parts need to be updated, but we don't have access to the old site.

It would make sense to have an updated version of that 8-based webpage, and we're looking for contributors who want to help with that.

**Comment by abhinayagarwal** [comment]
Closing as this is not an issue.
