### ISSUE TITLE
Add SQLite dependencies to runtime image

### ISSUE THREAD

**Issue by TarasTarghanskiy** [openjfx/openjfx-docs#197]
when I added "requires sqlite.jdbc;" to the project module and used javafx:jlink i got an issue:

"Error: automatic module cannot be used with jlink: sqlite.jdbc from file:///C:/Users/LenovoL340/.m2/repository/org/xerial/sqlite-jdbc/3.34.0/sqlite-jdbc-3.34.0.jar"

Does it mean that there is no way to use jlink and many of maven dependencies together?

I added a custom module to sqlite-jdbc-3.34.0.jar and just got another   error

**Comment by abhinayagarwal** [comment]
You don't have to add all your dependencies to the jlink runtime and package the application using `jpackage`. The docs would make it clear once we update them under #196.
