### ISSUE TITLE
Add specific sections for IDEs

### ISSUE THREAD

**Issue by jperedadnr** [openjfx/openjfx-docs#20]
Providing screenshots on how to create the project on each IDE, with ant, maven and gradle.

**Comment by DJViking** [comment]
Earch IDE meaning Eclipse, NetBeans and IntelliJ?

**Comment by jperedadnr** [comment]
Yes, those are the initial IDEs that will be included. PRs with other options are welcome of course. There is a PR #21 already for IntelliJ, feel free to review, test or provide feedback.

**Comment by DJViking** [comment]
Do you have a template of what the tutorials should contain? Probably to keep somewhat similar layout and composition among the different tutorials. Has anyone begun to compose an Eclipse tutorial? I could perhaps contribute something to this.
