### ISSUE TITLE
Program not compiled when the command "javac --module-path %PATH_TO_FX% --add-modules javafx.controls Game.java" is run

### ISSUE THREAD

**Issue by amateur-coder-1002** [openjfx/openjfx-docs#200]
I followed the instructions [here](https://openjfx.io/openjfx-docs/#install-javafx) to install JavaFX. I downloaded the runtime and added it to "Program Files" in the same folder I've got the Java runtime on. The path to this folder is as follows...
"C:\Program Files\Java\javafx-sdk-11.0.2\lib"

However, when I try compiling a program using,
`javac --module-path %PATH_TO_FX% --add-modules javafx.controls Game.java`

I get the error message:
```
error: invalid flag: Files\Java\javafx-sdk-11.0.2\lib
Usage: javac <options> <source files>
use --help for a list of possible options
```

I assume the reason for this is because the folder "Program Files" has got a space in its name that's because when I substitute the path, within quotation marks, to the JavaFX runtime to %PATH_TO_FX% in the command to compile above, the program is compiled. It's true that this way, the program is compiled successfully, however it would be convenient to have to specify the environment variable name of the path than typing the entire path itself.

**Comment by danielpeintner** [comment]
Duplicate of https://github.com/openjfx/openjfx-docs/issues/193 ?

**Comment by amateur-coder-1002** [comment]
Yeah, it sure is. Thanks
