### ISSUE TITLE
Add how-to for deployment

### ISSUE THREAD

**Issue by shathor** [openjfx/openjfx-docs#25]
Add a section that explains how to deploy a JavaFX application.

Some points to consider:
* Main-class that doesn't extend `Application` (for now)
* Building a (runnable) jar or fat-jar including JavaFX using Maven / Gradle
* Cross-platform by adding classifier in Maven / something equivalent in Gradle
* Modular vs non-modular JavaFX application

See: https://github.com/javafxports/openjdk-jfx/issues/236

**Comment by jperedadnr** [comment]
Have you seen the recent updated docs? There is a section called [modular](https://openjfx.io/openjfx-docs/#modular) that explains in great detail how to work with modular apps from command line, or with Maven/Gradle. 
At the end of it there is a link to a fat-jar document, that explains how to run non-modular apps from command line or with Maven/Gradle, and how to create a fat-jar.

The docs link to the samples [repo](https://github.com/openjfx/samples), where you can find all samples, including some comments about having cross-platform solutions.

So I guess this issue can be closed? Or am I missing something?

**Comment by shathor** [comment]
Yes I think the issue can be closed, thanks.

However I didn't expect that "Non-modular application" in the "Creating modular projects" section. I think it deserves its own.

**Comment by jperedadnr** [comment]
The "modular" section has been renamed to "Runtime images" and includes a few sub-sections for modular and non-modular projects. Hope this makes it more clear.
