### ISSUE TITLE
Simplify OS detection

### ISSUE THREAD

**Issue by miho** [openjfx/openjfx-docs#27]
Currently, almost a third of the sample `build.gradle` script is doing OS detection. Why not simplify things? The same can be achieved by

    def osName = System.getProperty("os.name").toLowerCase()
    ext.platform = osName.contains("mac") ? 'mac' : osName.contains("win") ? 'win' : osName;

Or does the osdetector anything special related to Android and iOS?

The problem here is that people starting with JavaFX & Gradle often use copy & paste to create their first build script or update JavaFX projects to Java 11. And they'd have to merge potential `buildscript {..}` blocks from other gradle scripts even though it's not really needed.

**Comment by mwkroening** [comment]
There is this related issue: https://github.com/openjfx/openjfx-docs/issues/6

**Comment by miho** [comment]
Thanks for the heads-up. I don't get the discussion about internal Gradle API vs. plugin since one can always get OS information with just a simple `System.getProperty("os.name")`. A plugin would only make sense if it returns the correct classifier strings (without the need for the ternary-operator stuff) or is used to deal with more complex stuff like architecture etc.

**Comment by jperedadnr** [comment]
We are working on a [plugin](https://github.com/openjfx/javafx-gradle-plugin) that will take care of classifiers, traversal dependencies, module-path... It has just been published and we need to do some tests yet, but it will be used to replace the existing approach in the docs.

**Comment by miho** [comment]
Cool, the plugin looks nice.
