### ISSUE TITLE
must modify nbactions.xml in modular Maven project as well

### ISSUE THREAD

**Issue by Cenbe** [openjfx/openjfx-docs#37]
On the page https://openjfx.io/openjfx-docs/, "JavaFX and NetBeans", "Modular with Maven", step 2, don't you also have to modify nbactions.xml as in step 2 of "Non-modular with Maven"?

**Comment by jperedadnr** [comment]
You are right, the same is required for modular projects, but actually the sample has the correct [pom](https://github.com/openjfx/samples/blob/master/IDE/NetBeans/Modular/Maven/hellofx/nbactions.xml). 
For the modular part, it is assumed (maybe wrongly) that you have read first the non-modular part, and it is much succinct. 

If you think this is still something that should be added to the docs, we can keep this issue open.

**Comment by jperedadnr** [comment]
Fixed by #41
