### ISSUE TITLE
Gradle 5.0 is out. Pointing to it or let 4.10+ in the page "Run HelloWorld using Gradle"

### ISSUE THREAD

**Issue by Naoghuman** [openjfx/openjfx-docs#48]
Gradle 5.0 (https://jaxenter.com/gradle-5-152369.html) is out.

In the page "Run HelloWorld using Gradle" the note points to 4.10+. 
- Should the version for gradle wrapped into 'span class=GRADLE_VERSION' into js/gluon.js (var GRADLE_VERSION = "5.0";)?
- Then the note can rebuild to some like "Make sure to use gradle version &lt;span class="GRADLE_VERSION"&gt;5.0&lt;/span&gt;+ and set the JAVA_HOME environment variable to JDK &lt;span class="JDK_MAJOR"&gt;11&lt;/span&gt;."

The `javafx-gradle-plugin` points to gradle-4.10.2-all.zip.

**Comment by jperedadnr** [comment]
It would be good if we test the samples with 5.0 before we do all these changes.

**Comment by jperedadnr** [comment]
I've raised a PR to the samples project, upgrading gradle wrappers to 5.0. I don't think we need a change in the docs, as you will rely on the wrapper. Basically we say you need a recent gradle version (which is probably not even required).
