### ISSUE TITLE
JavaFX libs are not in libs folder after running jlink

### ISSUE THREAD

**Issue by aizuchi0** [openjfx/openjfx-docs#49]
After following the directions under "JavaFX and Netbeans -> Modular from IDE", the application builds and jlink runs successfully, but I get the "Error initializing QuantumRenderer: no suitable pipeline found" error due to the JavaFX libs (in my case Mac *.dylib files) not being in the jlink'ed lib directory. If I manually copy them to that dir, the application runs. Suggestions?

**Comment by jperedadnr** [comment]
If you read the section 6. Create a custom runtime image:

> To create a runtime image, create a global Library under NetBeans -> Tools -> Libraries -> New Library. Name it JavaFXMODS11 and include the folder with the JavaFX jmods 11.0.1. Add this library to NetBeans -> Properties -> Libraries -> Run -> Modulepath.

you need to use the jmods instead of the SDK to generate the custom image, if you use the SDK the native libs won't be included.

See also this: https://stackoverflow.com/questions/52966195/custom-jre-with-javafx-11
