### ISSUE TITLE
Project examples have gone missing

### ISSUE THREAD

**Issue by bowring** [openjfx/openjfx-docs#56]
this link (and similar) are bad: https://openjfx.io/CommandLine/Non-modular/Gradle

**Comment by bowring** [comment]
When I visit https://openjfx.io/openjfx-docs/#maven and refresh and then go to the Runtime Images / Modular with Gradle section and click on the hypertext link for project in the following sentence:
"You can run or create a runtime of your JavaFX 11 Gradle project. A simple example can be found in this project."

It takes me to: https://openjfx.io/CommandLine/Modular/Gradle . which is also shown as the content of the hyperlink by the browser before clicking

This location returns a 404

**Comment by jperedadnr** [comment]
That works for me, it takes me to https://github.com/openjfx/samples/tree/master/CommandLine/Modular/Gradle

As I mentioned, the string "https://github.com/openjfx/samples/blob/master"  is [appended](https://github.com/openjfx/openjfx-docs/blob/master/js/gluon.js#L138) to every link.

It might be the case that the js function don't work for you? Platform/Browser?

**Comment by Naoghuman** [comment]
Works for me at:
* Windows 10
* Firefox / 63.0.3 (64-Bit)

At work I remember I have the same problem that the script doesn't work in all cases when I refresh the page. I must look at the version from the Firefox at work (I only now it's not the newest). I will add the info next monday.

**Comment by jperedadnr** [comment]
It should be fixed with #80
