### ISSUE TITLE
Linux/Mac-Windows tabs selection doesn't work

### ISSUE THREAD

**Issue by jperedadnr** [openjfx/openjfx-docs#57]
There Linux/Mac tab should be preselected, as the code shows the Linux/Mac configuration. And all the tabs from all the docs should use that preselection. When the user changes it, all tabs should change as well.

Somehow this is broken now.

**Comment by jperedadnr** [comment]
Issue related to this [commit](https://github.com/openjfx/openjfx-docs/commit/090a91d0fc257c48545d90f537766800c2f219ef#diff-fa64b4f4d049f81ca3a3b21ce56fe6beR92),  where `nav-link` classes from the menu conflict with the ones from the html docs.

**Comment by Naoghuman** [comment]
I can verify this wrong behaviour under:
* Windows 10
* Firefox 63.0.3 (64-Bit)

No tab is preselected:
![wrong-preselection](https://user-images.githubusercontent.com/8161815/49329460-6ccfa780-f57f-11e8-9227-4ae753ad3bcc.png)
