### ISSUE TITLE
dead links in "Run HelloWorld using JavaFX 11" page

### ISSUE THREAD

**Issue by negste** [openjfx/openjfx-docs#59]

**Comment by negste** [comment]
The links in "Compile the application (e.g. use HelloFX.java from this sample) using" give 404 error.
They point to https://openjfx.io/HelloFX/CLI/hellofx/HelloFX.java and https://openjfx.io/HelloFX/CLI

**Comment by jperedadnr** [comment]
Duplicated of #56
