### ISSUE TITLE
Missing 'tags' in the GitHub project openjfx/docs.

### ISSUE THREAD

**Issue by Naoghuman** [openjfx/openjfx-docs#64]
Missing 'tags' in the GitHub project openjfx/docs.
In `openjfx/samples` following tags are used:
- openjfx
- javafx
- javafx-11
- java
- java-11
- examples
- documentation
- maven
- gradle
- netbeans
- intellij
- eclipse
- modular
- ide
- non-modular

**Comment by tiainen** [comment]
I've added the same list of topics.
