### ISSUE TITLE
WebView fails to create

### ISSUE THREAD

**Issue by hmyzak** [openjfx/openjfx-docs#67]
Hello,

I try to migrate my project from the commercial Oracle JDK to the OpenJDK. I use the OpenJDK 11 and OpenJFX 11.0.1. When I try to create a new WebView object

view = new WebView();

program ends with th following exception:

_Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: superclass access check failed: class com.sun.javafx.sg.prism.web.NGWebView (in unnamed module @0x3fc77788) cannot access class com.sun.javafx.sg.prism.NGGroup (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.sg.prism to unnamed module @0x3fc77788
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)_

**Comment by jperedadnr** [comment]
If you don't post how you get that error, it won't be possible to reproduce it and help you. Edit your post with your settings: platform, build tools (and pom or build.gradle) and your command line options (module-path, add-module, ...).

**Comment by hmyzak** [comment]
===============Code===========================
```
package bug;
import javafx.application.Application;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
public class Bug extends Application {
  @Override
  public void start(Stage _primaryStage) {
    for (String key : System.getProperties().stringPropertyNames()) {
      System.err.println(key + " : " + System.getProperties().getProperty(key));
    }
    System.err.flush();
    WebView wv = new WebView();
  }
  public static void main(String[] _args) {
    launch(_args);
  }
}
```
================Environment======================
awt.toolkit : sun.awt.X11.XToolkit
java.specification.version : 11
javafx.runtime.version : 11.0.1+1
sun.cpu.isalist : 
sun.jnu.encoding : UTF-8
java.class.path : /home/nobody/javafx-sdk/lib/javafx-swt.jar:/home/nobody/javafx-sdk/lib/javafx.base.jar:/home/nobody/javafx-sdk/lib/javafx.controls.jar:/home/nobody/javafx-sdk/lib/javafx.fxml.jar:/home/nobody/javafx-sdk/lib/javafx.graphics.jar:/home/nobody/javafx-sdk/lib/javafx.media.jar:/home/nobody/javafx-sdk/lib/javafx.swing.jar:/home/nobody/javafx-sdk/lib/javafx.web.jar:/home/nobody/NetBeansProjects/Bug/build/classes
java.vm.vendor : Oracle Corporation
sun.arch.data.model : 64
java.vendor.url : http://java.oracle.com/
user.timezone : 
os.name : Linux
java.vm.specification.version : 11
javafx.version : 11.0.1
sun.java.launcher : SUN_STANDARD
user.country : US
sun.boot.library.path : /home/nobody/jdk/lib
sun.java.command : bug.Bug
jdk.debug : release
sun.cpu.endian : little
user.home : /home/nobody
user.language : en
java.specification.vendor : Oracle Corporation
jdk.module.path : /home/nobody/javafx-sdk/lib/javafx-swt.jar:/home/nobody/javafx-sdk/lib/javafx.base.jar:/home/nobody/javafx-sdk/lib/javafx.controls.jar:/home/nobody/javafx-sdk/lib/javafx.fxml.jar:/home/nobody/javafx-sdk/lib/javafx.graphics.jar:/home/nobody/javafx-sdk/lib/javafx.media.jar:/home/nobody/javafx-sdk/lib/javafx.swing.jar:/home/nobody/javafx-sdk/lib/javafx.web.jar
java.version.date : 2018-10-16
java.home : /home/nobody/jdk
file.separator : /
java.vm.compressedOopsMode : Zero based
line.separator : 

java.specification.name : Java Platform API Specification
java.vm.specification.vendor : Oracle Corporation
java.awt.graphicsenv : sun.awt.X11GraphicsEnvironment
sun.management.compiler : HotSpot 64-Bit Tiered Compilers
java.runtime.version : 11.0.1+13
user.name : nobody
path.separator : :
os.version : 4.15.0-42-generic
java.runtime.name : OpenJDK Runtime Environment
file.encoding : UTF-8
java.vm.name : OpenJDK 64-Bit Server VM
java.vendor.version : 18.9
java.vendor.url.bug : http://bugreport.java.com/bugreport/
java.io.tmpdir : /tmp
java.version : 11.0.1
user.dir : /home/nobody/NetBeansProjects/Bug
os.arch : amd64
java.vm.specification.name : Java Virtual Machine Specification
java.awt.printerjob : sun.print.PSPrinterJob
sun.os.patch.level : unknown
java.library.path : /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
java.vendor : Oracle Corporation
java.vm.info : mixed mode
java.vm.version : 11.0.1+13
sun.io.unicode.encoding : UnicodeLittle
java.class.version : 55.0

**Comment by hmyzak** [comment]
here you are:
--module-path /home/nobody/javafx-sdk/lib --add-modules=javafx.controls

**Comment by jperedadnr** [comment]
This is mentioned at the beginning of the [docs](
https://openjfx.io/openjfx-docs/#install-javafx): 

> Note: Additional modules are required for extended functionality. For example, if your application is using FXML, you will need to add the javafx.fxml module, as shown below:
javac --module-path $PATH_TO_FX --add-modules=javafx.controls,javafx.fxml HelloFX.java

This is the case of the web module, you need to add it too.
