### ISSUE TITLE
Getting started instructions for modular NetBeans project produce an invalid image

### ISSUE THREAD

**Issue by vic0824** [openjfx/openjfx-docs#68]
I have followed the instructions contained in the getting started page, creating a modular project in Netbeans ("Modular from IDE" section).
In particular, I have followed the instructions contained in Section 6 to add the JavaFX jmods to the module path, but it seems that the jmods have not been used to create the image. When I run it, I get the error on the initialisation of the quantum renderer.
The output of the Ant build file is also suspicious, because it mentions the JavaFX jars instead of the jmods:
```
To run this application from the command line without Ant, try:
C:\Program Files\Java\jdk-11.0.1/bin/java -modulepath C:\Program Files\Java\javafx-sdk-11.0.1\lib\javafx-swt.jar;C:\Program Files\Java\javafx-sdk-11.0.1\lib\javafx.base.jar;C:\Program Files\Java\javafx-sdk-11.0.1\lib\javafx.controls.jar;C:\Program Files\Java\javafx-sdk-11.0.1\lib\javafx.fxml.jar;C:\Program Files\Java\javafx-sdk-11.0.1\lib\javafx.graphics.jar;C:\Program Files\Java\javafx-sdk-11.0.1\lib\javafx.media.jar;C:\Program Files\Java\javafx-sdk-11.0.1\lib\javafx.swing.jar;C:\Program Files\Java\javafx-sdk-11.0.1\lib\javafx.web.jar;C:\Users\VTorroni\OneDrive - Serco\SW Projects\_libs\jexcelapi-2.6.12\modules\jxl.jar;C:\Users\VTorroni\Documents\NetBeansProjects\CryoStats\build\modules;C:\Program Files\Java\javafx-jmods-11.0.1 cryostats.CryoStats
deploy:
jar:
BUILD SUCCESSFUL (total time: 10 seconds)
```
If I follow the instructions for Eclipse, the image runs fine. The difference between the two images is that the image generated by NetBeans does not contain the following files:

- decora_sse.dll
- glass.dll
- javafx_font.dll
- javafx_iio.dll
- prism_common.dll
- prism_d3d.dll
- prism_sw.dll

**Comment by vic0824** [comment]
The sample project downloaded from github works.
I have compared the project files and found a crucial difference.
In the project.properties file of the sample project from github, the run.modulepath property has the following value:
```
run.modulepath=\
    ${libs.JavaFXMODS11.classpath}:\
    ${javac.modulepath}:\
    ${build.modules.dir}
```
whereas the run.modulepath property generated by NetBeans following the instructions in the tutorial is:
```
run.modulepath=\
    ${javac.modulepath}:\
    ${build.modules.dir}:\
    ${libs.JavaFXMODS11.classpath}
```

Apparently, the order in which the paths are specified is important: if I move  ${libs.JavaFXMODS11.classpath} at the beginning of the string, the packaging step generates a correct image.
Given that this file is generated automatically by NetBeans, I wonder how it is possible that the order is different in the sample project.

**Comment by jperedadnr** [comment]
Yes, the order is important, indeed. However, the order can be modified when you add the library. 

See updated document https://openjfx.io/openjfx-docs/#IDE-NetBeans, section Modular from IDE:

> Add this library to NetBeans -> Properties -> Libraries -> Run -> Modulepath and place it on top.

![](https://openjfx.io/openjfx-docs/images/ide/netbeans/modular/ide/netbeans04.png)
