### ISSUE TITLE
document 404

### ISSUE THREAD

**Issue by xvusrmqj** [openjfx/openjfx-docs#70]
all link in the page: https://openjfx.io/openjfx-docs/#maven is 404 .  as follows
![default](https://user-images.githubusercontent.com/2316516/51109876-9859d900-1831-11e9-8162-6817fc91a211.png)

**Comment by xvusrmqj** [comment]
It is 404 agin now .  this maybe the github problem. can openjfx not site on github pages?

**Comment by jperedadnr** [comment]
It should be fixed with #80
