### ISSUE TITLE
Add support for ogg audio on webview

### ISSUE THREAD

**Issue by giflw** [openjfx/openjfx-docs#73]
This was a request since JavaFX 8. I know some will say that ogg is old, but mp3 is old too. Ogg audio is a better format for streaming and can be used in lower bit rates than mp3 with higher quality when compared with same bit rate on mp3. It is a open format. It have a wide usage on Linux platform. Please, add support for it.

**Comment by jperedadnr** [comment]
Please, report this to https://github.com/javafxports/openjdk-jfx/issues
