### ISSUE TITLE
paths with spaces and modular/command_line section (win) | installation dirs for JavaFX

### ISSUE THREAD

**Issue by zemiak1** [openjfx/openjfx-docs#78]
https://openjfx.io/openjfx-docs/#install-javafx
examples with **Windows** tab (Win 7)

note 1:
[**Runtime images/Modular from CLI**]
  [**Command Line**]
`dir /s /b src\*.java > sources.txt & javac --module-path %PATH_TO_FX% -d mods/hellofx @sources.txt & del sources.txt`

If there is path with **space in name**, sources.txt must be (manually) edited and corrected with **quotes** "" for each path and` \ `replaced with `\\`

note 2:
This command (in the same section), works only without **quotes** ""
(I have path with space in name)
 `java --module-path "%PATH_TO_FX%;mods" -m hellofx/hellofx.HelloFX`
correct:
` java --module-path %PATH_TO_FX%;mods -m hellofx/hellofx.HelloFX`

same this next
[jlink]
`jlink --module-path "%PATH_TO_FX_MODS%;mods" --add-modules=hellofx --output hellofx`

notice:
[Run HelloWorld using JavaFX 11]
 `set PATH_TO_FX="path\to\javafx-sdk-11.0.2\lib"`
 defines variable with quotes "" yet !

note 3:
When I installed JavaFX 11, first I intuitive copy JavaFX files to Java SE dirs, because there is files with same names and directories. 
When I try compile and run sample HelloFX then it throws exception:
`Error occurred during initialization of boot layer java.lang.LayerInstantiationException: Package jdk.internal.jimage.decompressor in both module java.base and module jrt.fs`

When I remove .`.lib\jrt-fs.jar` from original Java installation it works, but I don't know if it is problem somewhere other.
Then I restore original Java SE installation and copy JavaFX-sdk and JavaFX-jmods to separated dirs, out of Java SE dirs, and it works.
But installation help needs to explicitly say about right way of installation.

**Comment by abhinayagarwal** [comment]
@zemiak1 Please find the response to your points below:

1. It is the responsible of the user to correctly add quotes("") to a path while executing on Windows.
2. This seems incorrect behaviour. Can you please a PR for the same?
3. The suggested approach is to not put JavaFX jmods/SDK inside your JDK. Therefore the guide suggests the users to set a separate "PATH_TO_FX" environment variable.

**Comment by abhinayagarwal** [comment]
No updates from reporter
