### ISSUE TITLE
I can't get javafx to run on my computer

### ISSUE THREAD

**Issue by RaddG93** [openjfx/openjfx-docs#79]
I followed the getting started with eclipse to the best of my ability. however I keep getting this error when I try to run the gui class.

Error: Could not find or load main class Files\Java\javafx-sdk-11.0.2\lib
Caused by: java.lang.ClassNotFoundException: Files\Java\javafx-sdk-11.0.2\lib

any help would be very much appreciated! thanks

**Comment by zemiak1** [comment]
When you defining path to javafx, use **quotes** "" (at start and at end of path), because you have space in the name (Program Files). I think in manual for windows is quotes too.

**Comment by RaddG93** [comment]
Wow It worked! Such a simple fix! Thank you so much!!! ...Yeah I overlooked the fact that I was looking at the tab for Linux/Mac on the instructions and not Windows. lol I can't believe I wasted hours on this haha. Anyways thanks again!!!
