### ISSUE TITLE
Intellij Run Config -> VM options path

### ISSUE THREAD

**Issue by jeevaka-4** [openjfx/openjfx-docs#81]
JavaFX and Intellij
-> Modular projects
--> 5. Add VM Options (Windows)
This didn't work for me:
--module-path "%PATH_TO_FX%;mods\production"
This worked:
--module-path "${PATH_TO_FX};mods\production"
i.e. same as linux. Not sure if this has to do with Intellij version or bitness.

**Comment by jperedadnr** [comment]
If you check the doc for JavaFX and IntelliJ non-modular projects, 4 add VM options, 
there it is explained that you can define `${PATH_TO_FX};` as global variable in IntelliJ, and you can use it later on to define the VM options. See pic: 

![](https://openjfx.io/openjfx-docs/images/ide/intellij/ide/idea08.png)

However, in the context of modular project 5 add VM options, we use `$PATH_TO_FX` for Linux/Mac and `%PATH_TO_FX%` for Windows as defined at the beginning of the tutorial, so the user will replace this variable (which is not valid for IntelliJ) with its value, like in the picture:

![](https://openjfx.io/openjfx-docs/images/ide/intellij/modular/ide/idea03.png)
