### ISSUE TITLE
JavaFX 11 + jGRASP: "Runtime components are missing"

### ISSUE THREAD

**Issue by jkhuggins** [openjfx/openjfx-docs#82]
I'm trying to install and run JavaFX 11 to work with JDK 11 on a Windows 10 machine using jGRASP 2.

I've been following the "Getting Started" directions (https://openjfx.io/openjfx-docs/) as well as I can, given that there isn't a set of directions for jGRASP.    I'm trying to compile and run HelloFX.java in the directions.

I've downloaded the ZIP and unpacked the JAR files, added the necessary JARs to the classpath, and added the following flags both to the compile and runtime commands, as instructed:

> --module-path` "C:\Program Files\Java\javafx-sdk-11.0.2\lib" --add-modules=javafx.controls,javafx.fxml

HelloFX.java will compile successfully.   However, when I try to run it, I get the familiar error message:

> Error: JavaFX runtime components are missing, and are required to run this application

The "Getting Started" document says that I can fix that problem by including the --module-path and --add-modules flags above.    But I've already done that, in both places.   I'm at a loss as to how to proceed.

(No, I don't know how to use maven, or IntelliJ, or NetBeans, or Eclipse.)

**Comment by jperedadnr** [comment]
I've posted an [answer](https://stackoverflow.com/questions/54662129/javafx-11-javafx-runtime-components-are-missing/54677356#54677356) at StackOverflow with the steps to run the HelloFX sample.

Can you verify if those work for you?

**Comment by jkhuggins** [comment]
As you posted this, I just received the same instructions from an independent source (i.e. the FLAGS2 solution) and confirmed that it works.    I was about to type it up, but your StackOverflow answer was much more extensive. 

Thanks for the help.
