### ISSUE TITLE
Error:Java FX Packager: Can't build artifact - fx:deploy is not available in this JDK

### ISSUE THREAD

**Issue by Maybelater2019** [openjfx/openjfx-docs#83]
When i try to build a application an error is appropriate: "Error:Java FX Packager: Can't build artifact - fx:deploy is not available in this JDK".

 I have seen some other documentation how to fix it, but its isn't worth. :(

**Comment by kevinrushforth** [comment]
You must be using an older JDK / FX build. there is no FX packager in the latest openjfx code.

**Comment by Maybelater2019** [comment]
Is there no other ways or must it be a older version?

**Comment by Maybelater2019** [comment]
> You must be using an older JDK / FX build. there is no FX packager in the latest openjfx code.
