### ISSUE TITLE
CGLChoosePixelFormat & CGLCreateContextError error on HelloFX test in VM 

### ISSUE THREAD

**Issue by philfrei** [openjfx/openjfx-docs#84]
When running the tutorial HelloFX test in VirtualBox (6.0) with Windows host, Mac High-Sierra guest, I get errors. A Java window opens but is empty. Here is the Terminal session text:

```
Phils-iMac:install-verification-test philfrei$ $JAVA_HOME/bin/javac --module-path $PATH_TO_FX --add-modules=javafx.controls HelloFX.java
Phils-iMac:install-verification-test philfrei$ $JAVA_HOME/bin/java --module-path $PATH_TO_FX --add-modules=javafx.controls HelloFX
2019-02-21 14:59:09.914 java[2210:56698] CGLChoosePixelFormat error: 10002
2019-02-21 14:59:09.914 java[2210:56698] CGLCreateContext error: 10002
```

I had success installing and running OpenJDK 11 and OpenJFX 11.0.2, using your tutorial example HelloFX, on my PC, on a Linux-guest VM (on a different PC), and on a friend's MacOS.

A custom, self-contained program that I made and that runs on my friend's Mac (made with the same software) generates the same error when running on this VM with the Mac-guest.

A test program using Swing does not generate this error and run as expected.

Is this a known problem with the VM context? I understand this environment might not be supported.

**Comment by jperedadnr** [comment]
Indeed, it looks like VM are [not supported](https://bugs.openjdk.java.net/browse/JDK-8154148?focusedCommentId=13926401&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13926401). Anyway, feel free to open an issue [here](https://github.com/javafxports/openjdk-jfx/issues).
