### ISSUE TITLE
Error:Java FX Packager: Can't build artifact - fx:deploy is not available in this JDK

### ISSUE THREAD

**Issue by Maybelater2019** [openjfx/openjfx-docs#90]
I do not understand the meaning behind it. I downloaded the JavaFX 11 module and used it to program and create programs. It does not look like that. I have not downloaded JavaFX 11 **for nothing**. If I click on Run button from my IDE everything works. Except to create programs. As it is already in the title, then an error is thrown out when I try to create a program or several programs.

-
**Error: Java FX Packager: Can not build artifact - fx: deploy is not available in this JDK**
-

**Comment by jperedadnr** [comment]
The `fx:deploy` option shipped with IntelliJ does not longer work with Java 11+, since there is no `JavaFX packager` since Java 8 nor `javapackager` since Java 10. 

There is an [issue](https://youtrack.jetbrains.com/issue/IDEA-200721) already filed on this at the IntelliJ issue tracker.

Options to create an installer are mentioned here https://openjfx.io/openjfx-docs/#modular. Also you can try the new `jpackage` tool which is still ea: http://jdk.java.net/jpackage/

**Comment by jefersontramonti** [comment]
quando pede a Packager no intellij o que devo colocar?

**Comment by Candra-2019-2020** [comment]
@jperedadnr  **Will JavaFX be added again? I cannot create JavaFX jar!!!**

**Comment by Candra-2019-2020** [comment]
I want to create JavaFX jars that allow other users to open .jar files with two clicks!

**Comment by patoessy** [comment]
There is javafx packager in java 8. But was removed in java 11. You can use
one in jdk 14. But its in incubation. Head over to java.net and see the
documentation

**Comment by JavaFX-Fan** [comment]
I can no longer create jar files and run them on other computers with two clicks! When will this bug be fixed?!

**Comment by atultiwariatul** [comment]
For me (Ubuntu+Intellij Idea+OpenJDK 14) what Worked is:

1. I created a Main.java file and called my Launcher.java file (JavaFX Application Main)
2. Go to Artifacts (Intellij Idea) and delete the older Artifacts configuration.
3. In the Artifacts section of your Projects Settings click to add a new Artifact
4. Select Jar->from modules with dependencies
5. Select Main.java file (Which is calling your Launcher.java file)
6. Select Extract the target jar.
7. Choose META-INF directory to generate the Meta inf information 

The Hack is that Intellij won't be treating this project as JavaFX application but as a Normal java project so it will generate the fat artifact successfully.
Please let me know if any step is not clear.

**Comment by AgainPsychoX** [comment]
`Error: JavaFX runtime components are missing, and are required to run this application`

**Comment by lzkovacs** [comment]
> `Error: JavaFX runtime components are missing, and are required to run this application`
Don't forget to add modules:
java --module-path /lib/javasdk/javafx-sdk-17.0.0.1/lib --add-modules javafx.controls,javafx.fxml -jar MyApp.jar

in this way worked, thank you @atultiwariatul

**Comment by hoangnguyen02** [comment]
> > `Error: JavaFX runtime components are missing, and are required to run this application`
> > Don't forget to add modules:
> > java --module-path /lib/javasdk/javafx-sdk-17.0.0.1/lib --add-modules javafx.controls,javafx.fxml -jar MyApp.jar
> 
> in this way worked, thank you @atultiwariatul

Hello, how can Exporting a javaFx project with libraries in eclipse? I have tried everything
