### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by kdyhj** [openjfx/openjfx-docs#93]
D:\다운로드>javac --module-path %PATH_TO_FX% --add-modules=javafx.controls,javafx.fxml HelloFX.java
HelloFX.java:1: error: class, interface, or enum expected
癤퓁mport javafx.application.Application;
^
1 error

D:\다운로드>java --module-path %PATH_TO_FX% --add-modules=javafx.controls HelloFX
Error: Could not find or load main class HelloFX
Caused by: java.lang.ClassNotFoundException: HelloFX

**Comment by jperedadnr** [comment]
Impossible to say what is happening unless you provided more info:

- Java version
- JavaFX version
- Value of `PATH_TO_FX`
- Content of your folder `D:\다운로드`

**Comment by jperedadnr** [comment]
I'm closing this issue due to lack of details or a way to reproduce it. Feel free to open it again with the required information.
