### ISSUE TITLE
error after running the helloFxx app

### ISSUE THREAD

**Issue by yassersaadi** [openjfx/openjfx-docs#99]
Error:(3, 26) java: cannot access javafx.application.Application
  bad class file: E:\javafx-sdk-12.0.1\lib\javafx.graphics.jar(javafx/application/Application.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by jperedadnr** [comment]
That error indicates your JDK is set to 1.8. You need to set JAVA_HOME to JDK 11 or 12.
